// Generated by build/generate-i18n.ts. Do not edit directly.

export const defaultLocale = "en";

export const messages = {
  en: {
    nav: {
      stores: "Stores",
    },
    stores: {
      title: "Stores",
    },
  },
  hr: {
    nav: {
      stores: "Trgovine",
    },
    stores: {
      title: "Trgovine",
    },
  },
} as const;
